name: flask
channels:
  - defaults
dependencies:
  - ca-certificates=2022.07.19
  - certifi=2022.6.15
  - openssl=1.1.1q
  - pip=22.1.2
  - python=3.7.13
  - setuptools=63.4.1
  - sqlite=3.39.2
  - wheel=0.37.1
  - pip:
    - boto3==1.26.45
    - botocore==1.29.45
    - cffi==1.15.1
    - charset-normalizer==2.1.1
    - click==8.1.3
    - colorama==0.4.5
    - cryptography==38.0.4
    - flask==2.2.2
    - flask-cors==3.0.10
    - flask-jwt-extended==4.4.4
    - greenlet==1.1.3.post0
    - idna==3.3
    - importlib-metadata==4.12.0
    - itsdangerous==2.1.2
    - jinja2==3.1.2
    - jmespath==1.0.1
    - markupsafe==2.1.1
    - numpy==1.21.6
    - pandas==1.3.5
    - pycparser==2.21
    - pyjwt==2.6.0
    - pymysql==1.0.2
    - pyopenssl==22.1.0
    - python-dateutil==2.8.2
    - python-dotenv==0.21.1
    - pytz==2022.5
    - requests==2.28.1
    - s3transfer==0.6.0
    - six==1.16.0
    - sqlalchemy==1.4.42
    - typing-extensions==4.3.0
    - urllib3==1.26.12
    - werkzeug==2.2.2
    - zipp==3.8.1